### ISSUE TITLE
Some little tips

### ISSUE THREAD

**Issue by Neboer** [iMyOwn/ipgw#23]
初次使用ipgw的时候，它提示我“配置文件格式不正确”，而此时我并没有任何的配置文件。当我ipgw fix后，它提示我重置成功，然后我添加了登录账号，-u xxx -p xxx -s，结果它提示配置文件格式不正确。很奇怪。

第二点，ipgw的密码输入采用命令行明文，这种方法既不安全又不科学，希望能用专门的密码输入方式来输入密码。

以上。

**Comment by iMyOwn** [comment]
第一点已经在Refactor分支修复，即将上线
第二点并无需求，因为几乎所有用户只要输入一次密码即可快速登陆，并且不希望引入交互式输入的功能

**Comment by Neboer** [comment]
确实，golang缺乏一个简单高效的类似于getpass()之类的函数，的确难以加上这种功能。我找机会实现一下。
