### ISSUE TITLE
无此命令: ipgw config 请使用 ipgw help 查看帮助信息

### ISSUE THREAD

**Issue by Binohow** [iMyOwn/ipgw#47]
![image](https://user-images.githubusercontent.com/43533177/148628771-5572dfcd-7f46-4f31-97af-b62a902f6205.png)

**Comment by amtoaer** [comment]
你的`ipgw`是新安装的吗，感觉像是很久前的版本（（

**Comment by unbyte** [comment]
不会是前年的版本吧(，建议删掉然后根据 https://github.com/neucn/ipgw#windows 安装一下新版

**Comment by Binohow** [comment]
本地版本        v1.3.1
获取最新版本信息中...
获取失败

**Comment by amtoaer** [comment]
ipgw 重写过一次，版本从 0.1.0 开始，如今最新版本是 0.2.0。你那里的 1.3.1 是重写前的版本，内置更新已经失效了 XD
> 建议删掉然后根据 https://github.com/neucn/ipgw#windows 安装一下新版

**Comment by Binohow** [comment]
确实是的，我这边把之前版本删除了，然后重新调整了一下系统变量，可以使用了！谢谢您！

**Comment by amtoaer** [comment]
没事没事，帮到你就好 🤣
