### ISSUE TITLE
not in campus network

### ISSUE THREAD

**Issue by rangehow** [iMyOwn/ipgw#56]
这个项目使我的科研生活便利了很多，非常感谢 : )
但是最近我碰上了一个问题，想求助一下项目的维护者们。实验室有一台在学校机房的服务器,在昨天断电维护之前他的IP地址是219.216.64.106，断电重启之后变成了219.216.64.13， 然后再使用本项目就产生了如下的错误信息：
```bash
using account '账号'
login failed: 
        not in campus network
```
但我想它应该是在校园网里的，不然我应该不能远程连接到他。有什么可能的排查路径吗，我查看了一下还开放的issue，尝试了一下curl 公网地址再ipgw，但是仍然不好使:(
提前感谢，砰砰

**Comment by Neboer** [comment]
能请你在目标机器上执行一下以下命令，看看输出结果？
```bash
curl https://ipgw.neu.edu.cn/cgi-bin/rad_user_info -H "Accept: application/json"
```

**Comment by rangehow** [comment]
> 能请你在目标机器上执行一下以下命令，看看输出结果？
> 
> ```shell
> curl https://ipgw.neu.edu.cn/cgi-bin/rad_user_info -H "Accept: application/json"
> ```
结果如下所示：
`curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to ipgw.neu.edu.cn:443 `

**Comment by Neboer** [comment]
可以证实，当前校园网的网络环境不稳定，我也存在这个问题。可以连接到外网，但不能连接到ipgw。

**Comment by Neboer** [comment]
校园网本身是稳定的，程序运行正常。不过如果要是命令行中有代理软件设置的环境变量则可能无法登录。请问您有开启什么代理软件吗？请检查命令行中
```
http_proxy
HTTP_PROXY
https_proxy
HTTPS_PROXY
```
环境变量的值。

**Comment by rangehow** [comment]
> 不对，校园网本身是稳定的，请问您有开启什么代理软件吗？

天呐确实qaq ，之前没注意我看了一下clash的日志把这个请求转发了，关掉就好使了，感谢

**Comment by Neboer** [comment]
不客气，祝你工作顺利。
